### ISSUE TITLE
Background downloads

### ISSUE THREAD

**Issue by BattlePizza** [NHMoeDev/NHentai-android#47]
Currently it takes more than 5 minutes to download a book, and meanwhile I can't do anything with my phone. Please include background download and if possible, multi-thread download as well.

**Comment by NotCR** [comment]
Hi @BattlePizza, with 1.6.3 i moved downloading books to the background (I had that in my mind for a long time) , you should now be able to continue using the phone. Apart from that i think multi-thread can be used, going to start checking that.

P.S: What do you think of the app (Perfomance / UX) ? have some ideas to make it better?

**Comment by BattlePizza** [comment]
Hi, thanks for letting me know, glad to hear it!
As for the UX, I think it's good enough for now, although I think if you can add a default language filter that can be set in settings it will be great!

**Comment by BattlePizza** [comment]
Also, probably an auto update system for the app? Or at least a notification of new versions available so we know when to update?

**Comment by NotCR** [comment]
Thanks for the feedback. I am actually working in the auto update feature (Notification + redirect link ). And the default language sounds interesting, going to give it thought.

**Comment by BattlePizza** [comment]
Yea, because sometimes things in languages that you don't understand mix in and stuff, you know.

**Comment by wightwulf1944** [comment]
I think this issue can be closed now. Tested in 1.8.4 beta 36
